eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb  # URL de connexion JDBC pour la base de données MySQL.
    password: root  # Mot de passe pour la base de données.
    username:   # Nom d'utilisateur pour la connexion à la base de données.
    driver-class-name: com.mysql.cj.jdbc.Driver  # Classe du pilote JDBC pour MySQL.
  jpa:
    hibernate:
      ddl-auto: update  # Stratégie de gestion du schéma de base de données (ici, mise à jour sans détruire les données).
    show-sql: true  # Si true, Hibernate affiche les requêtes SQL dans les logs.
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Dialecte spécifique pour MySQL avec moteur InnoDB.
